# Selecting the base Image - Like inheritance in programming
# Select the docker from DockeHub - https://hub.docker.com/
FROM alpine:latest

# Copy files from local directory into the app direcotry in the image
COPY . /app

WORKDIR /app

# Executing Commands
# CMD python /app/app.py
CMD python app.py